version: '3.3'
services:
  master:
    image: crawlabteam/crawlab
    container_name: crawlab_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - /Users/yzr-mac/Desktop/td_work/log:/home/log    # 挂载数据文件，根据实际路径修改 ：前的路径 test
  mongo:
    image: mongo:4.2
